import Head from 'next/head'
import Image from 'next/image'
import Cart from '../components/Cart'
import Header from '../components/Header'
import Panel from '../components/HomeCom/Panel'
import ServicesCards from '../components/HomeCom/ServicesCards'
import SmallCards from '../components/HomeCom/SmallCards'
import LoginForm from '../components/LoginForm'
import SingUpForm from '../components/SignUpForm'
import apiRequest from '../Server/ApiRequest'
import { useCustomHook } from '../service/Context'


export default function Home({ services }) {
  const { cartToggle, loginToggle, signUpToggle } = useCustomHook();
  return (
    <div className='w-[100%] h-fit min-h-[100vh] bg-gray-50/50 text-slate-700'>

      <Head>
        <title>Hodan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Panel />
      <section>
        {
          cartToggle && <Cart />
        }
        {signUpToggle && <SingUpForm />}
        {loginToggle && <LoginForm />}
      </section>
      <section className='w-[80%] overflow-auto m-auto py-10'>
        <h1 className='text-3xl font-normal text-center mb-10'>Services</h1>
        <div className='overflow-auto grid grid-cols-1 sm:grid-cols-3 gap-10'>
          {
            services?.map((value, index) => {
              return (
                <SmallCards {...value} key={index} />
              )
            })
          }
        </div>
      </section>
    </div>
  )
}


export async function getServerSideProps() {
  let data;
  const response = await apiRequest.get('/services')
    .catch(error => console.log('error ayaa dhacay', error))
  if (response) {
    data = response.data
  }
  return {
    props: {
      services: data
    }
  }
}